import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter/services.dart';
import '../core/config.dart';
import '../core/api.dart';import '../core/loading.dart';import '../core/push.dart';import '../core/ui.dart';import 'shell.dart';import 'manager_shell.dart';import 'admin_shell.dart';
class LoginScreen extends StatefulWidget{const LoginScreen({super.key});@override State<LoginScreen> createState()=>_LoginScreenState();}
class _LoginScreenState extends State<LoginScreen>{static const _legalChannel=MethodChannel('com.mleysoft.aidat/legal_browser');int tab=0;bool busy=false,hide=true,otpSent=false,register=false,locationsBusy=false;String? err,province,district;List<Map<String,dynamic>> provinces=[];List<String> districts=[];final email=TextEditingController(),pw=TextEditingController(),phone=TextEditingController(),otp=TextEditingController(),name=TextEditingController(),site=TextEditingController(),regPhone=TextEditingController();
Future<void>_openLegal(String page)async{final base=AppConfig.legalUrl(page);final u=base.contains('?')?'$base&app=1':'$base?app=1';try{await _legalChannel.invokeMethod('open',{'url':u});}catch(_){if(mounted)setState(()=>err='Sayfa açılamadı.');}}
Widget _legalLinks()=>Wrap(alignment:WrapAlignment.center,spacing:4,runSpacing:2,children:[TextButton(onPressed:()=>_openLegal('gizlilik-politikasi.php'),child:const Text('Gizlilik Politikası',style:TextStyle(fontSize:11))),TextButton(onPressed:()=>_openLegal('kullanim-kosullari.php'),child:const Text('Kullanım Koşulları',style:TextStyle(fontSize:11))),TextButton(onPressed:()=>_openLegal('kvkk.php'),child:const Text('KVKK',style:TextStyle(fontSize:11)))]);
Future<void>managerLogin()async{await _run(()async{final d=await Api.request('login',method:'POST',auth:false,body:{'identifier':email.text.trim(),'password':pw.text});await _enter(d);});}
Future<void>sendOtp()async{await _run(()async{final d=await Api.request('resident-otp-request',method:'POST',auth:false,body:{'phone':phone.text.trim()});if(d['demo_login']==true&&d['token']!=null){await _enter(d);return;}if(mounted)setState(()=>otpSent=true);});}
Future<void>verifyOtp()async{await _run(()async{final d=await Api.request('resident-otp-verify',method:'POST',auth:false,body:{'phone':phone.text.trim(),'code':otp.text.trim()});if(d['selection_required']==true){final choices=List<Map<String,dynamic>>.from((d['choices'] as List).map((e)=>Map<String,dynamic>.from(e)));if(!mounted)return;final pick=await showModalBottomSheet<Map<String,dynamic>>(context:context,showDragHandle:true,builder:(x)=>SafeArea(child:ListView(shrinkWrap:true,padding:const EdgeInsets.all(16),children:[const Text('Dairenizi Seçin',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),...choices.map((r)=>Card(child:ListTile(title:Text('${r['site_name']}',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${r['block_name']} • Daire ${r['door_no']}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.pop(x,r))))])));if(pick==null)return;final selected=await Api.request('resident-select',method:'POST',auth:false,body:{'selection_token':d['selection_token'],'apartment_id':pick['apartment_id']});await _enter(selected);return;}await _enter(d);});}
Future<void>_loadProvinces()async{if(provinces.isNotEmpty)return;setState(()=>locationsBusy=true);try{final r=await http.get(Uri.parse('https://api.turkiyeapi.dev/v2/provinces?fields=id,name&limit=100')).timeout(const Duration(seconds:15));final j=jsonDecode(r.body);final rows=(j is Map?j['data']:j) as List;provinces=rows.map((e)=>Map<String,dynamic>.from(e)).toList();provinces.sort((a,b)=>a['name'].toString().compareTo(b['name'].toString()));}catch(_){err='İl listesi yüklenemedi. İnternet bağlantınızı kontrol edip tekrar deneyin.';}finally{if(mounted)setState(()=>locationsBusy=false);}}
Future<void>_loadDistricts(Map<String,dynamic> p)async{setState(()=>{province=p['name'].toString(),district=null,districts=[],locationsBusy=true});try{final r=await http.get(Uri.parse('https://api.turkiyeapi.dev/v2/provinces/${p['id']}/districts?fields=id,name&limit=1000')).timeout(const Duration(seconds:15));final j=jsonDecode(r.body);final rows=(j is Map?j['data']:j) as List;districts=rows.map((e)=>e['name'].toString()).toList();districts.sort();}catch(_){err='İlçeler yüklenemedi. Lütfen tekrar deneyin.';}finally{if(mounted)setState(()=>locationsBusy=false);}}
Future<void>doRegister()async{if(province==null||district==null){setState(()=>err='İl ve ilçe seçimi zorunludur.');return;}await _run(()async{final d=await Api.request('register',method:'POST',auth:false,body:{'site_name':site.text.trim(),'full_name':name.text.trim(),'email':email.text.trim(),'phone':regPhone.text.trim(),'province':province,'district':district,'password':pw.text});await _enter(d);});}
Future<void>_enter(Map<String,dynamic>d)async{await Api.saveToken(d['token']);final u=Map<String,dynamic>.from(d['user']);final role=(u['role']??'resident').toString();await Api.saveRole(role);try{await PushService.syncToken();}catch(_){}if(!mounted)return;Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>role=='manager'?const ManagerShell():role=='super_admin'?const AdminShell():const AppShell()),(_)=>false);}
Future<void>_run(Future<void> Function() f)async{setState(()=>{busy=true,err=null});try{await f();}catch(e){if(mounted)setState(()=>err=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext c)=>Scaffold(body:LoadingOverlay(loading:busy,child:Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0xFFF7FCEB),bg])),child:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:460),child:Column(children:[Image.asset('assets/images/brand_lockup.png',height:72),const SizedBox(height:24),Container(padding:const EdgeInsets.all(5),decoration:BoxDecoration(color:const Color(0xFFE9EDF2),borderRadius:BorderRadius.circular(17)),child:Row(children:[_tab('Yönetici Girişi',0,Icons.admin_panel_settings_rounded),_tab('Daire Girişi',1,Icons.home_rounded)])),const SizedBox(height:20),SoftCard(padding:const EdgeInsets.all(20),child:register?_register():tab==0?_manager():_resident()),const SizedBox(height:18),const Text('MleySoft • Güvenli Aidat Yönetimi',style:TextStyle(color:muted,fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:4),_legalLinks()]))))))));
Widget _tab(String t,int i,IconData icon)=>Expanded(child:InkWell(borderRadius:BorderRadius.circular(13),onTap:()=>setState(()=>{tab=i,register=false,err=null}),child:AnimatedContainer(duration:const Duration(milliseconds:180),padding:const EdgeInsets.symmetric(vertical:13),decoration:BoxDecoration(color:tab==i&&!register?ink:Colors.transparent,borderRadius:BorderRadius.circular(13)),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:18,color:tab==i&&!register?Colors.white:muted),const SizedBox(width:6),Text(t,style:TextStyle(fontWeight:FontWeight.w800,color:tab==i&&!register?Colors.white:muted))]))));
Widget _error()=>err==null?const SizedBox.shrink():Container(width:double.infinity,margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:danger.withValues(alpha:.08),borderRadius:BorderRadius.circular(12)),child:Text(err!,style:const TextStyle(color:danger,fontWeight:FontWeight.w600)));
Widget _manager()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Yönetici girişi',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:5),const Text('Süper admin ve site yöneticileri için.',style:TextStyle(color:muted)),const SizedBox(height:18),_error(),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'E-posta',prefixIcon:Icon(Icons.mail_rounded))),const SizedBox(height:12),TextField(controller:pw,obscureText:hide,decoration:InputDecoration(labelText:'Şifre',prefixIcon:const Icon(Icons.lock_rounded),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:managerLogin,child:const Text('Yönetici Girişi'))),TextButton(onPressed:()async{setState(()=>register=true);await _loadProvinces();},child:const Text('Hesabınız yok mu? Kayıt Ol'))]);
Widget _resident()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Daire sakini girişi',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:5),const Text('Şifre yok. Giriş anahtarınız WhatsApp mesajı olarak gelir.',style:TextStyle(color:muted,height:1.4)),const SizedBox(height:16),Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFFEFFFE8),borderRadius:BorderRadius.circular(13)),child:const Row(children:[Icon(Icons.chat_rounded,color:success),SizedBox(width:9),Expanded(child:Text('Kayıtlı cep telefonunuza 6 haneli tek kullanımlık kod gönderilir.',style:TextStyle(fontWeight:FontWeight.w700,color:ink)))])),const SizedBox(height:16),_error(),TextField(controller:phone,readOnly:otpSent,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Cep Telefonu',hintText:'05xx xxx xx xx',prefixIcon:Icon(Icons.phone_iphone_rounded))),if(otpSent)...[const SizedBox(height:12),TextField(controller:otp,keyboardType:TextInputType.number,maxLength:6,textAlign:TextAlign.center,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,letterSpacing:7),decoration:const InputDecoration(labelText:'WhatsApp Kodu',counterText:''))],const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:otpSent?verifyOtp:sendOtp,icon:Icon(otpSent?Icons.verified_user_rounded:Icons.send_rounded),label:Text(otpSent?'Kodu Onayla ve Giriş Yap':'WhatsApp Kodunu Gönder'))),if(otpSent)TextButton(onPressed:()=>setState(()=>{otpSent=false,otp.clear()}),child:const Text('Farklı numara kullan'))]);
Widget _register()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[IconButton(onPressed:()=>setState(()=>register=false),icon:const Icon(Icons.arrow_back_rounded)),const Expanded(child:Text('Yeni Yönetici Kaydı',style:TextStyle(fontSize:23,fontWeight:FontWeight.w900,color:ink)))]),const Text('Paket seçmeden hesabınızı oluşturun. İl ve ilçe seçimi zorunludur.',style:TextStyle(color:muted,height:1.4)),const SizedBox(height:16),_error(),TextField(controller:site,decoration:const InputDecoration(labelText:'Site / Apartman Adı *',prefixIcon:Icon(Icons.apartment_rounded))),const SizedBox(height:10),TextField(controller:name,decoration:const InputDecoration(labelText:'Ad Soyad *',prefixIcon:Icon(Icons.person_rounded))),const SizedBox(height:10),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'E-posta *',prefixIcon:Icon(Icons.mail_rounded))),const SizedBox(height:10),TextField(controller:regPhone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Telefon',prefixIcon:Icon(Icons.phone_rounded))),const SizedBox(height:10),DropdownButtonFormField<String>(value:province,isExpanded:true,decoration:const InputDecoration(labelText:'İl *',prefixIcon:Icon(Icons.location_city_rounded)),items:provinces.map((p)=>DropdownMenuItem(value:p['name'].toString(),child:Text(p['name'].toString()))).toList(),onChanged:locationsBusy?null:(v){final p=provinces.firstWhere((x)=>x['name'].toString()==v);_loadDistricts(p);}),const SizedBox(height:10),DropdownButtonFormField<String>(value:district,isExpanded:true,decoration:InputDecoration(labelText:'İlçe *',prefixIcon:const Icon(Icons.location_on_rounded),suffixIcon:locationsBusy?const Padding(padding:EdgeInsets.all(12),child:SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2))):null),items:districts.map((d)=>DropdownMenuItem(value:d,child:Text(d))).toList(),onChanged:province==null||locationsBusy?null:(v)=>setState(()=>district=v)),const SizedBox(height:10),TextField(controller:pw,obscureText:hide,decoration:const InputDecoration(labelText:'Şifre (en az 6 karakter) *',prefixIcon:Icon(Icons.lock_rounded))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:doRegister,child:const Text('Kaydı Oluştur ve Uygulamaya Gir')))]);
}
